# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: node common/scripts/install-run-rush.js install --no-link
    - run: node common/scripts/install-run-rush.js link
    - run: node common/scripts/install-run-rush.js update
    - run: node common/scripts/install-run-rush.js build --verbose
    - run: export CODECOV_TOKEN="1b50e2b4-d843-48eb-bec7-6665d283b783"
    - run: bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/7877012ffd85dfb7968f91b5992edd627483dfe0/codecov) -f packages/vue3-ssr/coverage/lcov.info -F vue3-ssr -i vue3-ssr
    - run: bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/7877012ffd85dfb7968f91b5992edd627483dfe0/codecov) -f packages/plugin-bem/coverage/lcov.info -F plugin-bem -i packages/plugin-bem
    - run: bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/7877012ffd85dfb7968f91b5992edd627483dfe0/codecov) -f packages/css-render/coverage/lcov/lcov.info -F css-render -i packages/css-render
